version: '3.8'
services:
  user-service:
    build: ./main/user
    ports:
      - "4001:4001"
    environment:
      - DB_URI=mongodb://user-db:27017/user-service
    depends_on:
      - user-db

  user-db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=user-service

  tests:
    build:
        context: ./main/user
        dockerfile: Dockerfile.test
    command: npm run test
    depends_on:
      - user-service

volumes:
  user-db-data: