version: '3.8'
services:
  server:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: spark
    volumes:
      - spark-db-data:/data/db

volumes:
  spark-db-data:
