version: '3.8'
services:
  server:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis-server

  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: spark
    volumes:
      - spark-db-data:/data/db

  redis-server:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  spark-db-data:
  redis-data:
